export const actionTypes = {
   GET_USERS: "GET_USERS",
   GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
   GET_USERS_FAILED: "GET_USERS_FAILED",

   CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
   CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
   CREATE_USER_FAILED: "CREATE_USER_FAILED",

   GET_NEWS: "GET_NEWS",
   GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
   GET_NEWS_FAILED: "GET_NEWS_FAILED",

   GET_ONE_NEWS: "GET_ONE_NEWS",
   GET_ONE_NEWS_SUCCESS: "GET_ONE_NEWS_SUCCESS",
   GET_ONE_NEWS_FAILED: "GET_ONE_NEWS_FAILED",

   EDIT_ONE_NEWS: "EDIT_ONE_NEWS",
   EDIT_ONE_NEWS_SUCCESS: "EDIT_ONE_NEWS_SUCCESS",
   EDIT_ONE_NEWS_FAILED: "EDIT_ONE_NEWS_FAILED",

   CREATE_NEWS_REQUEST: "CREATE_NEWS_REQUEST",
   CREATE_NEWS_SUCCESS: "CREATE_NEWS_SUCCESS",
   CREATE_NEWS_FAILED: "CREATE_NEWS_FAILED",
}


